travis:
  secure:
    BINSTAR_TOKEN: HPVErWKuMNaIdJKRnFV3mpF1rTie456d4ocfLaExaTR/6BluSGHJZ0OXWAOePMAQyoHceKJ2pWL40X8Yyu9g6gSF2dhEdLngs4Fv8LqJ/BYpQEEC9GbtpblwDgrcpA2t9BSP2cgq6iNWEr9uRiZzuEW7ObNh9sxQY1Ghvecu8tG/5aZZzbwevg8QnXCD4fGnB0TrQMCQvEdi+YAw4iyJnaQkgf0ReXlQu+/a7VPMiBtRAQ3U29J7jCAWVJ2VfrVUdC8RFPv2glnpaTK9Ce5xH54olM4i4vy6CixGWBf5EyXim3q22ETMyP3ogpde0p8y9VtDTszEit+S4aBT3N26MBkzauEZNTfnHzO67kCC8mRoWSI86EA+CEK1eBXAuFTGIWIma2tuvohSxbtidCV4oy3Zyf/bwS1GMXMHKlzHCOTsjSrMNhPwkrDH3hAz1N5SURULRuL7edzA2seiT9H5eYMLMjTxfP5u1G6J8HNIqUmw8oddLynou3zkSpd6NKqUsGREnOmoMzB+rPQAR3Cz5wyV3mnDaDMoUSmMm5/3WEiaY519eFC0kwVUjuZMZ+hX36hqVV6nnRbGd5z4Q/Bg1rYwVupMkHR72cZbL4iERzzuPir+fJ18RGksaOXWPqXiz0pzGZhBWgns40emM1aeRJ+AxEpWdt7jv2df0V2igsk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
